name: Goalify
description: "A social habit tracker where friends create groups, set a deadline, complete tasks for points, and compete on a live scoreboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  confetti: ^0.8.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  google_fonts: ^8.0.2

  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  fl_chart: ^1.1.1
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
    android: true
    ios: true
    image_path: assets/images/app_icon.png
    adaptive_icon_background: "#d42b28"


flutter:
  assets:
    - assets/icons.json
    - assets/images/placeholder.jpg
    - assets/workouts.json
    - assets/images/exercises/
  uses-material-design: true



Error detected in pubspec.yaml:
No file or variants found for asset: assets/images/default_group.jpg.