"""initial schema

Revision ID: 99881738d0c5
Revises: 
Create Date: 2026-09-20 12:15:21.525813
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '99881738d0c5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('daily_activities',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('tasks_done', sa.Integer(), nullable=False),
    sa.Column('tasks_total', sa.Integer(), nullable=False),
    sa.Column('focus_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_activities')),
    sa.UniqueConstraint('user_id', 'day', name=op.f('uq_daily_activities_user_id'))
    )
    with op.batch_alter_table('daily_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_activities_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_activities_user_id'), ['user_id'], unique=False)

    op.create_table('daily_tasks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('keep', sa.Boolean(), nullable=False),
    sa.Column('repeat_pattern', sa.String(length=16), nullable=False),
    sa.Column('custom_days', sa.Integer(), nullable=False),
    sa.Column('repeat_start_key', sa.String(length=10), nullable=True),
    sa.Column('weekly_days', sa.String(length=20), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('last_done_key', sa.String(length=10), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('limited_cycle_interval_days', sa.Integer(), nullable=True),
    sa.Column('limited_cycle_start_key', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_tasks'))
    )
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_weight_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workout_id', sa.String(length=64), nullable=False),
    sa.Column('bar_weight_kg', sa.Float(), nullable=False),
    sa.Column('tracked_includes_bar', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exercise_weight_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_weight_settings'))
    )
    with op.batch_alter_table('exercise_weight_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_weight_settings_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_weight_settings_workout_id'), ['workout_id'], unique=False)

    op.create_table('groups',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('invite_code', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_groups_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_invite_code'), ['invite_code'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('device_label', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('workout_splits',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('days', sa.String(length=500), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_splits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_splits'))
    )
    with op.batch_alter_table('workout_splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_splits_user_id'), ['user_id'], unique=False)

    op.create_table('group_members',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_members_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_members')),
    sa.UniqueConstraint('group_id', 'user_id', name=op.f('uq_group_members_group_id'))
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_user_id'), ['user_id'], unique=False)

    op.create_table('task_checklist_items',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['daily_tasks.id'], name=op.f('fk_task_checklist_items_task_id_daily_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_checklist_items'))
    )
    with op.batch_alter_table('task_checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_checklist_items_task_id'), ['task_id'], unique=False)

    op.create_table('workout_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workout_id', sa.String(length=64), nullable=False),
    sa.Column('split_id', sa.String(length=36), nullable=True),
    sa.Column('day', sa.String(length=40), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['split_id'], ['workout_splits.id'], name=op.f('fk_workout_logs_split_id_workout_splits'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_logs'))
    )
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_logs_logged_at'), ['logged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_logs_workout_id'), ['workout_id'], unique=False)

    op.create_table('workout_sets',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('parent_set_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('bar_weight_kg', sa.Float(), nullable=False),
    sa.Column('weight_includes_bar', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['workout_logs.id'], name=op.f('fk_workout_sets_log_id_workout_logs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_set_id'], ['workout_sets.id'], name=op.f('fk_workout_sets_parent_set_id_workout_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sets'))
    )
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sets_log_id'), ['log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sets_log_id'))

    op.drop_table('workout_sets')
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_logs_workout_id'))
        batch_op.drop_index(batch_op.f('ix_workout_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_logs_logged_at'))

    op.drop_table('workout_logs')
    with op.batch_alter_table('task_checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_checklist_items_task_id'))

    op.drop_table('task_checklist_items')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_group_id'))

    op.drop_table('group_members')
    with op.batch_alter_table('workout_splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_splits_user_id'))

    op.drop_table('workout_splits')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_invite_code'))

    op.drop_table('groups')
    with op.batch_alter_table('exercise_weight_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_weight_settings_workout_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_weight_settings_user_id'))

    op.drop_table('exercise_weight_settings')
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_tasks_user_id'))

    op.drop_table('daily_tasks')
    with op.batch_alter_table('daily_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_activities_day'))

    op.drop_table('daily_activities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
